spring:
  profiles:
    active: dev
  application:
    name: gateway-api
  datasource:
    url: jdbc:h2:mem:default
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

security:
  oauth2:
    client:
      client-id: client
      client-secret: 53cr3t
    authorization:
      jwt:
        key-value: s1gn1ngK3y

logging:
  level:
    org:
      springframework:
        security: DEBUG